export const colors = {
  surface: '#fcf9f4',
  surfaceContainer: '#f0ede9',
  surfaceContainerLow: '#f6f3ee',
  surfaceContainerLowest: '#ffffff',
  surfaceContainerHigh: '#ebe8e3',
  surfaceContainerHighest: '#e5e2dd',
  surfaceVariant: '#e5e2dd',
  onSurface: '#1c1c19',
  onSurfaceVariant: '#43474e',
  primary: '#002444',
  primaryContainer: '#1b3a5c',
  secondary: '#35675b',
  secondaryContainer: '#b6ebdb',
  tertiary: '#361d00',
  tertiaryFixed: '#ffdcbc',
  tertiaryFixedDim: '#ffb86b',
  outline: '#73777f',
  outlineVariant: '#c3c6cf',
  error: '#ba1a1a',
  errorContainer: '#ffdad6',
  white: '#ffffff',
};
